global:
  scrape_interval: 5s     # Scrape every 5 seconds
  scrape_timeout: 4s     # Wait up to 4s for a response

scrape_configs:
  - job_name: 'churn-api-render'
    metrics_path: '/metrics'
    scheme: http 
    static_configs:
      - targets: ['localhost:8000']