global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'churn-api-render'
    metrics_path: '/metrics'
    scheme: https 
    static_configs:
      # Replace this with your render url
      - targets: ['https://mlops-final-project-p939.onrender.com:443']