# prometheus.yml
global:
  scrape_interval: 5s  # Scrape every 5 seconds (fast for demo purposes)

scrape_configs:
  - job_name: 'fastapi_churn_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:7860']  # 'churn-api' is the container name we define below