global:
  scrape_interval: 60s    # Check every minute
  scrape_timeout: 30s     # Wait up to 30s for a response

scrape_configs:
  - job_name: 'churn-api-render'
    metrics_path: '/metrics'
    scheme: https 
    static_configs:
      - targets: ['mlops-final-project-p939.onrender.com:443']